version: '2.3'

services:

  end2endrl:
    image: end2endrl
    container_name: end2endrl
    working_dir: /data
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - PYTHONPATH=/data
    volumes:
      - ../:/data

    runtime: nvidia
    command: tail /dev/null -f
  tensorboard:
    image: tensorflow/tensorflow
    container_name: tensorboard
    working_dir: /logs
    ports:
     - "6006:6006"
    volumes:
      - ../src/tensorboard:/logs
    command: tensorboard --logdir /logs
