version: '2.3'

services:

  end2endrl:
    image: end2endrl
    container_name: end2endrl
    working_dir: /data
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - PYTHONPATH=/data
      - DISPLAY=unix$DISPLAY
      - HOST_PATH=$PWD
      - FLASK_ENV=development
      - FLASK_APP=/data/src/app.py
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - AWS_IP=18.191.153.175
    volumes:
      - ../:/data
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "5000:5000"
    runtime: nvidia
    # command: flask run
    command: tail /dev/null -f
  frontend:
    image: react
    container_name: frontend
    build:
      context: .
      dockerfile: ./Dockerfile_frontend
    volumes:
      - '../js-gui:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
  tensorboard:
    image: tensorflow/tensorflow
    container_name: tensorboard
    working_dir: /logs
    ports:
     - "6006:6006"
    volumes:
      - ../src/tensorboard:/logs
    command: tensorboard --logdir /logs
